### ISSUE TITLE
Bug - namespace without pod fails

### ISSUE THREAD

**Issue by lypht** [farmotive/kex#12]
When using kex, if a namespace is empty, it can still be accepted as an option, which then fails when the default pod is not found.  Testing for this would require querying all namespaces for pods before listing, which may be too much of a burden for the edge case.

**Comment by scottrigby** [comment]
Another POV… I felt that `kubectl exec`‘s default error handling seemed ok ¯\_(ツ)_/¯ so far I pretty much let all it’s existing errors do their thing. We can close if ppl agree. My argument is I like this because it keeps the codebase super simple.
