### ISSUE TITLE
Prompt to select container in a pod with sidecars

### ISSUE THREAD

**Issue by scottrigby** [farmotive/kex#15]

**Comment by lypht** [comment]
The stated use case for this demonstrated a need to use https://github.com/farmotive/klog.  We should consider the impact to the majority use case where an additional prompt is predominantly unnecessary, and detracts from the main purpose.

**Comment by scottrigby** [comment]
Absolutely. Only prompt for a container if there are more than one in the selected pod. 

I agree it's not a high-priority for me personally, but it's a valid use case - if it weren't `kubectl exec` wouldn't have the `--container` option ¯\_(ツ)_/¯
